version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - depixen-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=depixen-pass
    command: -p 5439
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5439", "-U", "postgres"]
      interval: 5s
      retries: 5

  api:
    build: ./depixen-services
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./depixen-webui
    ports:
      - "3000:3000"
    depends_on:
     - api


volumes:
  depixen-volume:
    driver: local

